### ISSUE TITLE
why do transcript profiles seem to show as max TPM = 1?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/CoNekT#2]
noticed this while prepping for single cell project meeting, logging before I forget. Here's a set of genes which seem to give very different results in the Mine heat map relative to what we see in conekt:
glyma.Wm82.gnm2.ann1.Glyma.01G165300
glyma.Wm82.gnm2.ann1.Glyma.02G047000
glyma.Wm82.gnm2.ann1.Glyma.11G077900
glyma.Wm82.gnm2.ann1.Glyma.16G126500

<img width="612" alt="image" src="https://github.com/legumeinfo/CoNekT/assets/2009605/4377013d-0165-40a4-a865-f877f418c45c">
vs
<img width="1010" alt="image" src="https://github.com/legumeinfo/CoNekT/assets/2009605/e511b9dc-70c4-42ec-9b33-3e36113822bd">
(not talking about the visual style differences)

**Comment by sdash-github** [comment]
At https://conekt.legumeinfo.org/profile_comparison/
There is checkbox below the input area, "Normalize plots?" which is selected by default. If unchecked the result shows the actual TPM for each sample. Otherwise, the max expressed gene in each profile is used for normalization.
- [ ] Normalize plots?  
The right hand side panel mentions this feature, "By default profiles are normalized against the most expressed gene in each profile (recommended). The checkbox allow you to disable this feature."

Without normalized selected (Stacey_Nodule):
11G077900 has tpm=143 which is red in profile and as a contrast 16G126500 has tpm=0 which shows up as darker blue in profile as expected per the heatmap scale.
Profile plot w/o normalization attached below.

![Screen Shot 2023-07-18 at 4 54 28 PM](https://github.com/legumeinfo/CoNekT/assets/3673723/18a691fd-080d-4d92-81a4-059bf06b8c4d)

**Comment by adf-ncgr** [comment]
Ah, OK I guess I missed seeing that checkbox. I think I understand the situation better now, thanks I'll close this.
